#!/usr/bin/env python3
"""Per-state contact-network metrics — audit §35 v26 / obj-066.

Graph-theoretic decomposition of obj-065 per-state contact maps.
Computes per-residue degree, per-state network density, and per-state
clustering coefficient (tendency for triangle-closure of contacts).

Loads `results/afm_pipeline/contact_map_per_state/contact_maps.npz`
generated by obj-065 (`pipelines/avb3-conformers/scripts/contact_map_per_state.py`).

Method:
  1. Per state s, threshold C_s at 0.5 → binary expected-contact graph.
  2. Per residue: degree d_s[i] = Σ_j A_s[i,j].
  3. Per residue: clustering coefficient
       cc_s[i] = (2·#triangles at i) / (d_s[i] · (d_s[i] - 1))
  4. Network density = mean d_s / (n_residues - 1).
  5. Identify "lonely" (Δd EC-BC most negative) and "social" (Δd
     EC-BC most positive) residues.

Output:
  - figures/contact_network_metrics_v1.png
  - results/afm_pipeline/contact_map_per_state/network_metrics.json
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[3]
NPZ = ROOT / "results" / "afm_pipeline" / "contact_map_per_state" / "contact_maps.npz"
OUT_JSON = ROOT / "results" / "afm_pipeline" / "contact_map_per_state" / "network_metrics.json"
OUT_FIG = ROOT / "figures" / "contact_network_metrics_v1.png"

STATE_NAMES = ["BC", "Inter", "EC"]
STATE_COLORS = ["#4a90e2", "#f5a623", "#d0021b"]
EXPECTED_CONTACT_THRESHOLD = 0.5
TOP_K = 12


def degree(A: np.ndarray) -> np.ndarray:
    return A.sum(axis=1)


def clustering_coef(A: np.ndarray) -> np.ndarray:
    """Local clustering coefficient per node.

    cc_i = (number of edges among neighbors of i) / (k_i choose 2)
    For binary symmetric A: triangles(i) = (A^3)[i,i] / 2.
    Number of edges among neighbors = (A^2)[i,i] / 2 ... actually
    a simpler formulation: for each i, the number of pairs (j, k)
    such that A[i,j] = A[i,k] = A[j,k] = 1 equals the number of
    triangles through i.

    Compute via: A2 = A @ A; for each i, triangles_i = (A2 * A)[i,].sum() / 2
    """
    A_int = A.astype(np.int32)
    A2 = A_int @ A_int
    triangle_count = (A2 * A_int).sum(axis=1) / 2.0
    k = degree(A_int).astype(float)
    denom = k * (k - 1) / 2.0
    cc = np.where(denom > 0, triangle_count / denom, 0.0)
    return cc


def main() -> int:
    print(f"Loading {NPZ.name} ...")
    d = np.load(NPZ)
    C_state = d["C_state"]
    head_chain = d["head_ca_chain"]
    head_resseq = d["head_ca_resseq"]

    n = C_state.shape[1]
    print(f"3 states × {n} CAs × {n}")

    A = (C_state >= EXPECTED_CONTACT_THRESHOLD).astype(np.int8)
    np.einsum("sii->si", A)[...] = 0  # zero diagonals

    print(f"\nThreshold: P(contact) ≥ {EXPECTED_CONTACT_THRESHOLD}")
    deg = np.zeros((3, n))
    cc = np.zeros((3, n))
    density = np.zeros(3)
    edge_count = np.zeros(3)
    cc_mean = np.zeros(3)
    for s in range(3):
        deg[s] = degree(A[s])
        cc[s] = clustering_coef(A[s])
        edge_count[s] = A[s].sum() / 2  # symmetric
        density[s] = edge_count[s] / (n * (n - 1) / 2)
        cc_mean[s] = cc[s].mean()
        print(f"  state {STATE_NAMES[s]:<5s}: edges={edge_count[s]:>6.0f}, "
              f"density={density[s]*100:5.2f}%, "
              f"⟨degree⟩={deg[s].mean():5.2f}, "
              f"⟨clustering⟩={cc_mean[s]:.4f}")

    # Differentials (EC − BC)
    delta_deg = deg[2] - deg[0]

    # Top-K most "lonely" (degree drops on extension)
    lonely_idx = np.argsort(delta_deg)[: TOP_K]
    social_idx = np.argsort(-delta_deg)[: TOP_K]

    def res_label(i: int) -> str:
        ch = "A" if head_chain[i] == 0 else "B"
        return f"{ch}:{int(head_resseq[i])}"

    lonely = [{
        "rank": k + 1,
        "ca_index_in_head": int(i),
        "residue": res_label(i),
        "deg_BC": float(deg[0, i]),
        "deg_Inter": float(deg[1, i]),
        "deg_EC": float(deg[2, i]),
        "delta_deg_EC_BC": float(delta_deg[i]),
        "cc_BC": float(cc[0, i]),
        "cc_EC": float(cc[2, i]),
    } for k, i in enumerate(lonely_idx)]
    social = [{
        "rank": k + 1,
        "ca_index_in_head": int(i),
        "residue": res_label(i),
        "deg_BC": float(deg[0, i]),
        "deg_Inter": float(deg[1, i]),
        "deg_EC": float(deg[2, i]),
        "delta_deg_EC_BC": float(delta_deg[i]),
        "cc_BC": float(cc[0, i]),
        "cc_EC": float(cc[2, i]),
    } for k, i in enumerate(social_idx)]

    print(f"\nTop-{TOP_K} 'lonely' residues (degree drops most on EC):")
    for r in lonely:
        print(f"  {r['rank']:>2d}  {r['residue']:>6s}  "
              f"BC={r['deg_BC']:>5.1f} → Inter={r['deg_Inter']:>5.1f} → EC={r['deg_EC']:>5.1f}  "
              f"Δ={r['delta_deg_EC_BC']:>+6.2f}")
    print(f"\nTop-{TOP_K} 'social' residues (degree gains most on EC):")
    for r in social:
        print(f"  {r['rank']:>2d}  {r['residue']:>6s}  "
              f"BC={r['deg_BC']:>5.1f} → Inter={r['deg_Inter']:>5.1f} → EC={r['deg_EC']:>5.1f}  "
              f"Δ={r['delta_deg_EC_BC']:>+6.2f}")

    out = {
        "n_residues": int(n),
        "expected_contact_threshold": EXPECTED_CONTACT_THRESHOLD,
        "edge_count": {STATE_NAMES[s]: float(edge_count[s]) for s in range(3)},
        "network_density_pct": {STATE_NAMES[s]: float(density[s] * 100) for s in range(3)},
        "mean_degree": {STATE_NAMES[s]: float(deg[s].mean()) for s in range(3)},
        "mean_clustering": {STATE_NAMES[s]: float(cc_mean[s]) for s in range(3)},
        "delta_density_EC_BC_pct": float((density[2] - density[0]) * 100),
        "delta_mean_degree_EC_BC": float(deg[2].mean() - deg[0].mean()),
        "delta_mean_clustering_EC_BC": float(cc_mean[2] - cc_mean[0]),
        "frac_clustering_loss_pct": float(
            (cc_mean[0] - cc_mean[2]) / cc_mean[0] * 100) if cc_mean[0] > 0 else 0.0,
        "top_lonely": lonely,
        "top_social": social,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with OUT_JSON.open("w") as f:
        json.dump(out, f, indent=2)
    print(f"\nsaved {OUT_JSON}")

    plot(deg, delta_deg, head_chain,
         lonely, social, density, cc_mean, edge_count)
    return 0


def plot(deg, delta_deg, head_chain,
         lonely, social, density, cc_mean, edge_count):
    fig = plt.figure(figsize=(15.5, 11.5))
    gs = fig.add_gridspec(3, 2, height_ratios=[1.2, 1.0, 1.0],
                          hspace=0.55, wspace=0.18)

    n = deg.shape[1]
    x = np.arange(n)
    chain_b_start = int(np.where(head_chain == 1)[0].min())

    # Top: per-residue degree per state
    ax = fig.add_subplot(gs[0, :])
    for s in range(3):
        ax.plot(x, deg[s], color=STATE_COLORS[s], linewidth=0.85,
                alpha=0.85,
                label=f"{STATE_NAMES[s]}: ⟨k⟩ = {deg[s].mean():.2f}, "
                      f"density = {density[s]*100:.2f}%, "
                      f"⟨cc⟩ = {cc_mean[s]:.3f}")
    ax.axvline(chain_b_start, color="red", linewidth=0.6, alpha=0.5,
               linestyle="--", label="α/β chain boundary")
    ax.set_xlabel("CA index (αV chain A → β3 chain B)")
    ax.set_ylabel("Degree (number of contacts)")
    ax.set_title(f"Per-residue contact degree per state (obj-066) — "
                 f"V1+V2 fitted; threshold P(contact) ≥ 0.5",
                 fontsize=11, fontweight="bold")
    ax.legend(loc="upper left", fontsize=9, framealpha=0.92)
    ax.grid(alpha=0.3)

    # Mid-left: Δ degree (EC-BC) per residue
    ax = fig.add_subplot(gs[1, 0])
    color_map = np.where(delta_deg < 0, "#4a90e2", "#d0021b")
    ax.bar(x, delta_deg, color=color_map, alpha=0.75, width=0.85)
    ax.axhline(0, color="black", linewidth=0.6)
    ax.axvline(chain_b_start, color="black", linewidth=0.6,
               alpha=0.5, linestyle="--")
    ax.set_xlabel("CA index")
    ax.set_ylabel("Δ degree (EC − BC)")
    n_lonely = int((delta_deg < 0).sum())
    n_social = int((delta_deg > 0).sum())
    ax.set_title(f"Δ degree per residue — {n_lonely} lonely (blue) / "
                 f"{n_social} social (red); mean Δ = {delta_deg.mean():.2f}",
                 fontsize=10, fontweight="bold")
    ax.grid(alpha=0.3)

    # Mid-right: per-state degree distribution histograms
    ax = fig.add_subplot(gs[1, 1])
    for s in range(3):
        ax.hist(deg[s], bins=range(0, int(deg.max()) + 2), density=True,
                color=STATE_COLORS[s], alpha=0.45, label=f"{STATE_NAMES[s]}")
    ax.set_xlabel("degree (number of contacts per residue)")
    ax.set_ylabel("density")
    ax.set_title("Per-state degree distribution",
                 fontsize=10, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)

    # Bottom: lonely + social residue tables side by side
    ax_lonely = fig.add_subplot(gs[2, 0])
    ax_lonely.axis("off")
    rows = [["#", "residue", "BC k", "Inter k", "EC k", "Δk"]]
    for r in lonely:
        rows.append([
            f"{r['rank']}",
            r["residue"],
            f"{r['deg_BC']:.0f}",
            f"{r['deg_Inter']:.0f}",
            f"{r['deg_EC']:.0f}",
            f"{r['delta_deg_EC_BC']:+.1f}",
        ])
    table = ax_lonely.table(cellText=rows, loc="center", cellLoc="center",
                             colWidths=[0.06, 0.20, 0.12, 0.16,
                                         0.12, 0.10])
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.0, 1.30)
    for k in range(len(rows[0])):
        table[(0, k)].set_text_props(weight="bold", color="white")
        table[(0, k)].set_facecolor("#444444")
    for i in range(1, len(rows)):
        for k in range(len(rows[0])):
            table[(i, k)].set_facecolor("#dde9f4")
    ax_lonely.set_title(
        f"Top-{TOP_K} 'lonely' residues (degree drops most on extension)",
        fontsize=10, fontweight="bold")

    ax_social = fig.add_subplot(gs[2, 1])
    ax_social.axis("off")
    rows = [["#", "residue", "BC k", "Inter k", "EC k", "Δk"]]
    for r in social:
        rows.append([
            f"{r['rank']}",
            r["residue"],
            f"{r['deg_BC']:.0f}",
            f"{r['deg_Inter']:.0f}",
            f"{r['deg_EC']:.0f}",
            f"{r['delta_deg_EC_BC']:+.1f}",
        ])
    table = ax_social.table(cellText=rows, loc="center", cellLoc="center",
                             colWidths=[0.06, 0.20, 0.12, 0.16,
                                         0.12, 0.10])
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.0, 1.30)
    for k in range(len(rows[0])):
        table[(0, k)].set_text_props(weight="bold", color="white")
        table[(0, k)].set_facecolor("#444444")
    for i in range(1, len(rows)):
        for k in range(len(rows[0])):
            table[(i, k)].set_facecolor("#fcdedb")
    ax_social.set_title(
        f"Top-{TOP_K} 'social' residues (degree gains most on extension)",
        fontsize=10, fontweight="bold")

    fig.suptitle(
        f"Per-state contact-network metrics (obj-066) — graph-theoretic "
        f"decomposition of obj-065 per-state contact maps\n"
        f"Edges: BC {edge_count[0]:.0f} → Inter {edge_count[1]:.0f} → "
        f"EC {edge_count[2]:.0f} (Δ = {edge_count[2] - edge_count[0]:+.0f}, "
        f"{(edge_count[2] - edge_count[0]) / edge_count[0] * 100:+.1f}%); "
        f"⟨clustering⟩ {cc_mean[0]:.3f} → {cc_mean[2]:.3f} "
        f"({(cc_mean[2] - cc_mean[0]) / cc_mean[0] * 100:+.1f}%)",
        fontsize=10.5, fontweight="bold", y=0.995,
    )

    OUT_FIG.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT_FIG, dpi=140, bbox_inches="tight")
    print(f"saved {OUT_FIG}")


if __name__ == "__main__":
    raise SystemExit(main())
