#!/usr/bin/env python3
"""Render PDB structures with confidence (pLDDT/B-factor) coloring via ChimeraX.

Generates publication-quality images of PDB structures colored by per-residue
confidence scores. Uses the AlphaFold-style coloring scheme:
  - Dark blue (pLDDT > 90): very high confidence
  - Light blue (70-90): high confidence
  - Yellow (50-70): low confidence
  - Orange (<50): very low confidence

If the PDB has B-factor values (e.g., from ESMFold/AlphaFold), uses those.
Otherwise can accept a separate pLDDT numpy array.

Usage:
    python render_confidence.py --pdb structure.pdb --output render.png
    python render_confidence.py --pdb-dir frames/ --output-dir renders/
    python render_confidence.py --pdb structure.pdb --plddt scores.npy --output render.png
"""
from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path


CHIMERAX_SCRIPT_TEMPLATE = """
# ChimeraX confidence rendering script
# Auto-generated by render_confidence.py

open "{pdb_path}"

# Use B-factor for coloring (pLDDT is typically stored in B-factor column)
color bfactor palette alphafold

# Set background and lighting
set bgColor white
lighting soft

# Ribbon representation with confidence coloring
hide atoms
show cartoons
color bfactor palette alphafold

# Camera setup - fit all and add some padding
view all

# Add color key legend
key alphafold pos 0.02,0.1 size 0.04,0.3 labelColor black fontSize 12 \\
    label "pLDDT" ticks true

# Save image
save "{output_path}" width {width} height {height} supersample 3 transparentBackground false

close all
"""

CHIMERAX_MULTI_VIEW_TEMPLATE = """
# ChimeraX multi-view rendering for comparing conformers
open "{pdb_path}"

color bfactor palette alphafold
set bgColor white
lighting soft
hide atoms
show cartoons

# Front view
view all
save "{output_dir}/{name}_front.png" width {width} height {height} supersample 3 transparentBackground false

# Side view (90 degree rotation)
turn y 90
save "{output_dir}/{name}_side.png" width {width} height {height} supersample 3 transparentBackground false

# Top view
turn y -90
turn x 90
save "{output_dir}/{name}_top.png" width {width} height {height} supersample 3 transparentBackground false

close all
"""


def inject_plddt_as_bfactor(pdb_path: Path, plddt_values: list[float],
                             output_path: Path) -> None:
    """Write a new PDB with pLDDT values in the B-factor column."""
    import numpy as np
    plddt = np.array(plddt_values)

    lines = []
    res_idx = -1
    prev_resid = None
    for line in pdb_path.read_text().splitlines():
        if line.startswith(("ATOM", "HETATM")):
            resid = line[22:27]  # chain + resseq
            if resid != prev_resid:
                res_idx += 1
                prev_resid = resid
            if res_idx < len(plddt):
                bfactor = f"{plddt[res_idx]:6.2f}"
            else:
                bfactor = f"{0.0:6.2f}"
            line = line[:60] + bfactor + line[66:]
        lines.append(line)

    output_path.write_text("\n".join(lines))


def render_pdb(pdb_path: Path, output_path: Path, plddt_path: Path | None = None,
               width: int = 1200, height: int = 900,
               multi_view: bool = False) -> bool:
    """Render a single PDB with confidence coloring."""
    # If pLDDT provided separately, inject into B-factor
    actual_pdb = pdb_path
    tmp_pdb = None
    if plddt_path is not None:
        import numpy as np
        plddt = np.load(str(plddt_path)).flatten().tolist()
        tmp_pdb = Path(tempfile.mktemp(suffix=".pdb"))
        inject_plddt_as_bfactor(pdb_path, plddt, tmp_pdb)
        actual_pdb = tmp_pdb

    output_path.parent.mkdir(parents=True, exist_ok=True)

    if multi_view:
        script = CHIMERAX_MULTI_VIEW_TEMPLATE.format(
            pdb_path=str(actual_pdb.resolve()),
            output_dir=str(output_path.parent.resolve()),
            name=output_path.stem,
            width=width, height=height,
        )
    else:
        script = CHIMERAX_SCRIPT_TEMPLATE.format(
            pdb_path=str(actual_pdb.resolve()),
            output_path=str(output_path.resolve()),
            width=width, height=height,
        )

    # Write script to temp file
    script_file = Path(tempfile.mktemp(suffix=".cxc"))
    script_file.write_text(script)

    try:
        result = subprocess.run(
            ["chimerax", "--offscreen", "--nogui", "--script", str(script_file)],
            capture_output=True, text=True, timeout=120,
        )
        success = result.returncode == 0
        if not success:
            print(f"  ChimeraX error for {pdb_path.name}: {result.stderr[:200]}")
        return success
    except subprocess.TimeoutExpired:
        print(f"  ChimeraX timeout for {pdb_path.name}")
        return False
    except FileNotFoundError:
        print("  ERROR: ChimeraX not found. Install or add to PATH.")
        return False
    finally:
        script_file.unlink(missing_ok=True)
        if tmp_pdb is not None:
            tmp_pdb.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pdb", type=Path, help="Single PDB to render.")
    parser.add_argument("--pdb-dir", type=Path, help="Directory of PDBs to render.")
    parser.add_argument("--output", type=Path, help="Output image path (single PDB).")
    parser.add_argument("--output-dir", type=Path, help="Output directory (batch).")
    parser.add_argument("--plddt", type=Path, default=None,
                        help="Numpy array of per-residue pLDDT scores.")
    parser.add_argument("--width", type=int, default=1200)
    parser.add_argument("--height", type=int, default=900)
    parser.add_argument("--multi-view", action="store_true",
                        help="Render front/side/top views.")
    parser.add_argument("--frame-indices", default=None,
                        help="Comma-separated frame indices to render (batch mode).")
    args = parser.parse_args()

    if args.pdb:
        if not args.output:
            args.output = args.pdb.with_suffix(".png")
        print(f"Rendering {args.pdb} → {args.output}")
        ok = render_pdb(args.pdb, args.output, args.plddt,
                       args.width, args.height, args.multi_view)
        return 0 if ok else 1

    elif args.pdb_dir:
        if not args.output_dir:
            args.output_dir = args.pdb_dir / "renders"
        args.output_dir.mkdir(parents=True, exist_ok=True)

        pdb_files = sorted(args.pdb_dir.glob("*.pdb"))
        if args.frame_indices:
            wanted = set(args.frame_indices.split(","))
            pdb_files = [f for f in pdb_files
                         if any(w in f.stem for w in wanted)]

        print(f"Rendering {len(pdb_files)} PDBs → {args.output_dir}")
        success = 0
        for pf in pdb_files:
            out = args.output_dir / f"{pf.stem}_confidence.png"
            if render_pdb(pf, out, None, args.width, args.height, args.multi_view):
                success += 1
                print(f"  ✓ {pf.name}")
            else:
                print(f"  ✗ {pf.name}")

        print(f"\nRendered {success}/{len(pdb_files)} PDBs")
        return 0

    else:
        parser.error("Provide --pdb or --pdb-dir")


if __name__ == "__main__":
    raise SystemExit(main())
